project:
  type: book
  output-dir: _book
  resources:
    - workshop/workshop.html
    - workshop/workshop_files/**
    - workshop/images/CodebookGenerator.png
    - workshop/images/DataCuration_Toolbox.png
    - workshop/images/extracted_p8_Image52.png
    - workshop/images/extracted_p8_Image53.png
    - workshop/images/extracted_p11_Image65.png
    - workshop/images/qr-code.png

book:
  title: "Research Data Curator’s Toolbox"
  subtitle: "Expert Workflows for Digital Curation & Preservation"
  author: "Curation Services Team | Digital Research Alliance of Canada"
  date: today
  chapters:
    - index.qmd

    - part: Code_and_Software.qmd
      chapters:
        - Inspect_ipynb_Notebook.qmd
        - Inspect_Code_Notebook.qmd

    - part: Documents.qmd
      chapters:
        - Inspect_PDF_Notebook.qmd
        - Inspect_Text_Notebook.qmd
        - Inspect_OCR_Notebook.qmd


    - part: Data_General.qmd
      chapters:
        - Inspect_Extensions_Notebook.qmd
        - Inspect_Containers_Notebook.qmd

    - part: Data_Tabular.qmd
      chapters:
        - Inspect_csv_Notebook.qmd
        - Inspect_xlsx_Notebook.qmd
        - Inspect_sav_Notebook.qmd
        - Inspect_dta_Notebook.qmd
        - Inspect_sas7bdat_Notebook.qmd
        - Inspect_sqlite_Notebook.qmd
        
    - part: Data_Structured.qmd
      chapters:
        - Inspect_json_Notebook.qmd
        - Inspect_xml_Notebook.qmd

    - part: Data_Scientific.qmd
      chapters:
        - Inspect_nc_Notebook.qmd
        - Inspect_hdf5_Notebook.qmd
        - Inspect_mat_Notebook.qmd
        
    - part: Data_Geospatial.qmd
      chapters:
        - Inspect_gpkg_Notebook.qmd
        
    - part: Data_Image.qmd
      chapters:
        - Inspect_Images_Notebook.qmd
        - Inspect_Tiff_Notebook.qmd

bibliography: references.bib
format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles/styles.css
    mainfont: "Montserrat"
    headerfont: "Ubuntu"
    toc-depth: 3
    code-copy: true
    code-tools: true

execute:
  echo: true
  warning: false
  message: false
  freeze: auto

editor: visual
