project:
  type: book
  output-dir: _book

book:
  title: "Tools for Research Data Management and curation"
  subtitle: "A Practical Guide for Data Curators"
  author: "Curation services team of the Digital Research Alliance of Canada"
  date: today
  chapters:
    - index.qmd

    - part: Data_General.qmd
      chapters:
        - FileChecks_Extensions_Notebook.qmd

    - part: Data_Tabular.qmd
      chapters:
        - FileChecks_csv_Notebook.qmd
        - FileOpen_xlsx_Notebook.qmd
        
    - part: Data_Scientific.qmd
      chapters:
        - FileOpen_gpkg_Notebook.qmd
        - FileOpen_nc_Notebook.qmd
        - FileOpen_mat_Notebook.qmd
        
        
    - part: Data_Image.qmd
      chapters:
        - FileChecks_Images_Notebook.qmd




bibliography: references.bib
format:
  html:
    theme:
      - cosmo
    css: styles/styles.css
    toc-depth: 3
    code-copy: true
    code-tools: true
  pdf:
    documentclass: scrbook
    geometry:
      - margin=1in
      - heightrounded
  docx:
    toc: true

execute:
  echo: true
  warning: false
  message: false
  freeze: auto

editor: visual
