#!/usr/bin/env Rscript

# ==============================================================================
# Script: Inspect_PPMstarRelease_Script.R
# Purpose: Structural completeness/consistency check for a PPMstar simulation
#          data release: release.json at the top, one <run>/ directory per
#          run with variables.json, prfs/ and moms/myavsbq/<dump>/
#          subfolders. Cross-checks the file counts and sizes the JSON
#          metadata claims against what is actually on disk, without reading
#          the large binary payloads themselves (those are covered by
#          Verify_ChecksumManifest_Script.R). The .rprof/.aaa internal byte
#          layout needs the depositor's own ppmpy package to decode and is
#          out of scope here.
#
# Is this layout specific to one dataset, or shared across PPMstar releases?
# Shared. This script is driven entirely by parsing release.json (no run
# names or other per-submission details are hardcoded), and the "moms" /
# "myavsbq" / "prfs" naming is generated by the PPMstar code and its official
# Python reader, not invented by any one depositor. Verified independently
# (2026-09-24), beyond the README of the dataset this script was first built
# against:
#   - PyPPM (aka ppmpy), the PPMstar collaboration's own reader for this
#     data, is maintained by the NuGrid collaboration:
#     https://github.com/PPMstar/PyPPM (docs: https://ppmstar.github.io/PyPPM/)
#   - PPMstar's own official example notebooks (PPMnotebooks repository,
#     https://github.com/PPMstar/PPMnotebooks) use the identical "myavsbq"
#     moms-cube directory name and "prfs/" radial-profile directory name for
#     a DIFFERENT, unrelated simulation project
#     ("N16-LowZRAWD-1536-10x-burn-moms/myavsbq" and
#     ".../prfs/", in Demos/MomsData_Mollweide_projection), confirming the
#     naming is a code/tooling convention, not something specific to the
#     O-shell dataset (FRDR 1777) this script was written for.
#   - PPMnotebooks also ships a dedicated "O-shell analysis" folder,
#     consistent with O-/C-shell convective-boundary studies being a
#     recurring PPMstar research theme with its own established data
#     conventions, not a one-off.
#   - Background on the PPMstar collaboration (Paul Woodward's Laboratory of
#     Computational Science and Engineering, University of Minnesota, with
#     Falk Herwig's group and collaborators) and its practice of releasing
#     large 3-D stellar hydrodynamics datasets (aggregate project volumes on
#     the order of 100s of TB) is described in Herwig et al. 2018,
#     "Cyberhubs: Virtual Research Environments for Astronomy", ApJS 236, 2:
#     https://doi.org/10.3847/1538-4365/aab777 (open text:
#     https://ar5iv.labs.arxiv.org/html/1802.02233).
# This script should therefore run as-is (no PPMstar-specific edits needed)
# on any future PPMstar release that follows the same release.json /
# variables.json / moms/myavsbq / prfs / frombqavs layout, not only 1777.
#
# Usage:   Rscript Inspect_PPMstarRelease_Script.R <release_directory> [output_dir]
#          <release_directory> is the folder containing release.json directly
#          (e.g. .../O-shell-data-release), not its parent.
# ==============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(jsonlite)
})

# 1. Setup & Arguments (Hybrid: Interactive / HPC) ------------------------------
if (interactive()) {
  message("Running in interactive mode. Please select a directory.")
  if (requireNamespace("rstudioapi", quietly = TRUE)) {
    target_dir <- rstudioapi::selectDirectory(caption = "Select PPMstar Release Directory")
  } else {
    stop("Package 'rstudioapi' is required for interactive selection.")
  }
  if (is.null(target_dir)) stop("No directory selected.")
  output_dir <- file.path(getwd(), "Results/Inspect_PPMstarRelease")
} else {
  args <- commandArgs(trailingOnly = TRUE)
  if (length(args) == 0) {
    stop("Error: No target directory provided.\nUsage: Rscript Inspect_PPMstarRelease_Script.R /path/to/release_dir [output_dir]", call. = FALSE)
  }
  target_dir <- args[1]
  if (!dir.exists(target_dir)) {
    stop(paste("Error: Directory not found:", target_dir), call. = FALSE)
  }
  output_dir <- if (length(args) >= 2) args[2] else file.path(getwd(), "Results/Inspect_PPMstarRelease")
}

if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
dir_label <- gsub("[^A-Za-z0-9_.-]", "_", basename(sub("[/\\\\]+$", "", target_dir)))

release_path <- file.path(target_dir, "release.json")
if (!file.exists(release_path)) {
  message(sprintf("No release.json found directly under %s. Exiting.", target_dir))
  quit(status = 0)
}
release <- fromJSON(release_path, simplifyDataFrame = FALSE)
message(sprintf("Loaded release.json: %d run(s) declared.", length(release$runs)))

# 2. Per-run checks ---------------------------------------------------------------
check_run <- function(run) {
  short <- run$short
  run_dir <- file.path(target_dir, short)
  issues <- character(0)

  if (!dir.exists(run_dir)) {
    return(tibble(Run = short, Check = "run_directory_exists", Expected = "exists", Actual = "MISSING", Status = "FAIL"))
  }

  rows <- list()

  # A. variables.json presence and cross-check against release.json's own claims
  varjson_path <- file.path(run_dir, "variables.json")
  if (!file.exists(varjson_path)) {
    rows[[length(rows) + 1]] <- tibble(Run = short, Check = "variables_json_exists", Expected = "exists", Actual = "MISSING", Status = "FAIL")
  } else {
    varjson <- tryCatch(fromJSON(varjson_path, simplifyDataFrame = FALSE), error = function(e) NULL)
    if (is.null(varjson)) {
      rows[[length(rows) + 1]] <- tibble(Run = short, Check = "variables_json_parses", Expected = "valid JSON", Actual = "PARSE ERROR", Status = "FAIL")
    } else {
      dumps_release <- as.integer(unlist(run$dumps))
      dumps_varjson <- as.integer(unlist(varjson$dumps))
      dumps_match <- identical(sort(dumps_release), sort(dumps_varjson))
      rows[[length(rows) + 1]] <- tibble(Run = short, Check = "dumps_list_matches_release_json",
                                          Expected = paste(length(dumps_release), "dumps"),
                                          Actual = paste(length(dumps_varjson), "dumps",
                                                          if (!dumps_match) "(LIST DIFFERS)" else "(identical)"),
                                          Status = if (dumps_match) "OK" else "FAIL")
    }
  }

  # B. flags.F and .include files present
  flags_file <- file.path(run_dir, run$flags)
  rows[[length(rows) + 1]] <- tibble(Run = short, Check = "flags_F_exists", Expected = run$flags,
                                      Actual = if (file.exists(flags_file)) "present" else "MISSING",
                                      Status = if (file.exists(flags_file)) "OK" else "FAIL")
  include_file <- file.path(run_dir, run$include)
  rows[[length(rows) + 1]] <- tibble(Run = short, Check = "include_file_exists", Expected = run$include,
                                      Actual = if (file.exists(include_file)) "present" else "MISSING",
                                      Status = if (file.exists(include_file)) "OK" else "FAIL")

  # C. moms/myavsbq: dump-folder count and per-file size check
  moms_dir <- file.path(run_dir, "moms", "myavsbq")
  n_dumps_expected <- length(run$dumps)
  if (!dir.exists(moms_dir)) {
    rows[[length(rows) + 1]] <- tibble(Run = short, Check = "moms_dir_exists", Expected = "exists", Actual = "MISSING", Status = "FAIL")
  } else {
    dump_dirs <- list.files(moms_dir, full.names = FALSE)
    rows[[length(rows) + 1]] <- tibble(Run = short, Check = "moms_dump_folder_count",
                                        Expected = as.character(n_dumps_expected),
                                        Actual = as.character(length(dump_dirs)),
                                        Status = if (length(dump_dirs) == n_dumps_expected) "OK" else "FAIL")

    # Dump numbers in the JSON are plain integers (e.g. 560); on-disk folder and
    # file names use 4-digit zero-padding (e.g. "0560"). Compare padded forms,
    # or a run with dump numbers under 1000 (e.g. O32, 560-569) produces a false
    # mismatch here even though nothing is actually wrong.
    dumps_padded <- sprintf("%04d", as.integer(unlist(run$dumps)))
    missing_dumps <- setdiff(dumps_padded, dump_dirs)
    extra_dumps <- setdiff(dump_dirs, dumps_padded)
    if (length(missing_dumps) > 0) {
      rows[[length(rows) + 1]] <- tibble(Run = short, Check = "moms_missing_dump_folders",
                                          Expected = "none", Actual = paste(missing_dumps, collapse = ", "), Status = "FAIL")
    }
    if (length(extra_dumps) > 0) {
      rows[[length(rows) + 1]] <- tibble(Run = short, Check = "moms_unexpected_dump_folders",
                                          Expected = "none", Actual = paste(extra_dumps, collapse = ", "), Status = "FAIL")
    }

    # File-size check: every moms sub-cube file must equal bytes_per_file
    expected_bytes <- run$bytes_per_file
    all_moms_files <- list.files(moms_dir, recursive = TRUE, full.names = TRUE)
    if (length(all_moms_files) > 0) {
      sizes <- file.size(all_moms_files)
      wrong_size <- all_moms_files[sizes != expected_bytes]
      rows[[length(rows) + 1]] <- tibble(Run = short, Check = "moms_file_count",
                                          Expected = as.character(n_dumps_expected * run$files_per_dump),
                                          Actual = as.character(length(all_moms_files)),
                                          Status = if (length(all_moms_files) == n_dumps_expected * run$files_per_dump) "OK" else "FAIL")
      rows[[length(rows) + 1]] <- tibble(Run = short, Check = "moms_file_sizes_match_bytes_per_file",
                                          Expected = paste0("all = ", expected_bytes, " bytes"),
                                          Actual = if (length(wrong_size) == 0) "all match" else paste(length(wrong_size), "file(s) differ:", paste(head(basename(wrong_size), 5), collapse = ", ")),
                                          Status = if (length(wrong_size) == 0) "OK" else "FAIL")
    }
  }

  # D. prfs/: file count vs release.json's declared prfs_files, and frombqavs/
  # dump range sanity (every file's embedded dump number should be one of the
  # run's RELEASED moms dumps, since that subfolder is documented as "spherical
  # averages of the released dumps").
  prfs_dir <- file.path(run_dir, "prfs")
  if (!dir.exists(prfs_dir)) {
    rows[[length(rows) + 1]] <- tibble(Run = short, Check = "prfs_dir_exists", Expected = "exists", Actual = "MISSING", Status = "FAIL")
  } else {
    prfs_all <- list.files(prfs_dir, recursive = TRUE, full.names = FALSE)
    n_prfs_actual <- length(prfs_all)
    n_prfs_expected <- run$prfs_files
    rows[[length(rows) + 1]] <- tibble(Run = short, Check = "prfs_total_file_count",
                                        Expected = as.character(n_prfs_expected),
                                        Actual = as.character(n_prfs_actual),
                                        Status = if (isTRUE(n_prfs_actual == n_prfs_expected)) "OK" else "FAIL")

    frombqavs_dir <- file.path(prfs_dir, "frombqavs")
    if (dir.exists(frombqavs_dir)) {
      frombqavs_files <- list.files(frombqavs_dir)
      dump_numbers <- as.integer(str_match(frombqavs_files, "(\\d{4})")[, 2])
      released_dumps <- as.integer(unlist(run$dumps))
      out_of_range <- frombqavs_files[!dump_numbers %in% released_dumps]
      rows[[length(rows) + 1]] <- tibble(Run = short, Check = "frombqavs_file_count",
                                          Expected = paste(n_dumps_expected, "(one per released dump)"),
                                          Actual = as.character(length(frombqavs_files)),
                                          Status = if (length(frombqavs_files) == n_dumps_expected) "OK" else "FAIL")
      if (length(out_of_range) > 0) {
        rows[[length(rows) + 1]] <- tibble(Run = short, Check = "frombqavs_dump_number_out_of_released_range",
                                            Expected = "all dump numbers within released set",
                                            Actual = paste(out_of_range, collapse = ", "), Status = "FAIL")
      }
    }
  }

  bind_rows(rows)
}

message("Checking each run...")
report <- map_dfr(release$runs, check_run)

# 3. Export --------------------------------------------------------------------
output_file <- file.path(output_dir, paste0("PPMstarRelease_Consistency_", dir_label, "_", format(Sys.Date(), "%Y%m%d"), ".csv"))
write_excel_csv(report, output_file)

n_fail <- sum(report$Status == "FAIL")
message(sprintf("Process complete. %d check(s) failed out of %d.", n_fail, nrow(report)))
if (n_fail > 0) {
  message("Failed checks:")
  report %>% filter(Status == "FAIL") %>% pwalk(function(Run, Check, Expected, Actual, Status) {
    message(sprintf("  [%s] %s: expected %s, got %s", Run, Check, Expected, Actual))
  })
}
message(paste("Report saved to:", output_file))
